In [ ]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
'''NumPy stands for Numerical Python.
   NumPy is a Python library used for working with arrays.
   It also has functions for working in domain of linear algebra, fourier transform, and matrices.
   Purpose 
   In Python we have lists that serve the purpose of arrays, but they are slow to process.
   NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
   The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
   Arrays are very frequently used in data science, where speed and resources are very important.
   Reason 
   Numpy is using c or c++ language so it's working fast than python.
   As it uses the homogenous data it is fast.
   since it store homogenous data in continous memory location, so mathematical computataion is fast.'''

In [ ]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
'''In the Numpy library, there are two functions np.mean() and np.average() are present.
   Both are actually doing nearly the same job of calculating mean/average. 
   The difference comes when we are calculating the weighted average. If that is the case then we have to use np.average(). 
   With np.average function we can calculate both arithmetic mean and weighted average.
   np.mean()
  np.mean(array_name, axis = none) 
  In numpy library, np.mean() is a function used to calculate arithmetic mean of the given array along with the axis.
  np.average()
  numpy.average(arr, axis = , weights = )
  The arithmetic mean and weighted average calculations are more flexible with np.average(). 
  It can calculate the weighted average if we pass the weight; if not, it returns the same value as np.mean(). '''

In [9]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Array is ",arr)
mean=np.mean(arr)
print("mean value is",mean)

Array is  [1 2 3 4 5 6 7 8 9]
mean value is 5.0


In [27]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array : ",arr,)
print("Mean of the Array : ",np.average(arr),)
weight = np.array([4,5,6,12,15,10,2,8,19,20])
print("Weight average of Array : ",np.average(arr, weights=weight))

Array :  [ 1  2  3  4  5  6  7  8  9 10]
Mean of the Array :  5.5
Weight average of Array :  6.574257425742574


In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
'''Using flip() function to Reverse a Numpy array
   The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.
   Using slicing of array
   This method makes a copy of the list instead of sorting it in order.
   To accommodate all of the current components, making a clone requires additional room. 
   More RAM is used up in this way.
   Using flipud function to Reverse a Numpy array 
   The numpy.flipud() function flips the array(entries in each column) in up-down direction, shape preserved.'''

In [35]:
arr=np.array([1,2,3,4,5])
print("The given array is ", arr,"\n")
rev1=np.flip(arr)
print(" Reverse of array using flip is",rev1,"\n")
rev2=arr[::-1]
print("Reverse of array using slicing",rev2,"\n")
rev3=np.flipud(arr)
print("Reverse of the array using flipud",rev3,"\n")

The given array is  [1 2 3 4 5] 

 Reverse of array using flip is [5 4 3 2 1] 

Reverse of array using slicing [5 4 3 2 1] 

Reverse of the array using flipud [5 4 3 2 1] 



In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
'''A data type in NumPy is used to specify the type of data stored in a variable.
  We can check the datatype of Numpy array by using dtype. Then it returns the data type all the elements in the array. '''

In [37]:
arr = np.array([1, 2, 3, 4, 5])
data_type = arr.dtype
print("Data type:", data_type)

Data type: int32


In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''What is a Numpy array?
    NumPy is the fundamental package for scientific computing in Python.
    Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. 
    Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. 
    Numpy is not another programming language but a Python extension module. It provides fast and efficient operations on arrays of homogeneous data. 
    We can create an N-dimensional array in Python using np.array().
   The array is by default Homogeneous, which means data inside an array must be of the same Datatype.
What is Python List?
   A Python list is a collection that is ordered and changeable. In Python, lists are written with square brackets. 
   The list can be homogeneous or heterogeneous.
   Element-wise operation is not possible on the list.
   Python list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
   Elements of a list need not be contiguous in memory.'''

In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
'''Memory usage
    The most important gain is the memory usage. This comes in handy when we implement complex algorithms and in research work.
  Speed
    Numpy is speed because it store the homogenous data in continous form.
  Memory consumption between Numpy array and lists 
     In Python, a list is a built-in data structure that can hold elements of varying data types. However, the flexibility of lists comes at the cost of memory efficiency.
     Python’s NumPy library supports optimized numerical array and matrix operations.

In [ ]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output
'''np.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.
   numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.'''

In [8]:
import numpy as np
arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n",arr1)  
arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n",arr2)   
arr = np.vstack((arr1,arr2)) 
print ("Output stacked array :\n ", arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


In [10]:
import numpy as np
arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n",arr1)  
arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n",arr2)   
arr = np.hstack((arr1,arr2)) 
print ("Output stacked array :\n ", arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
'''fliplr()
   Use np.fliplr() to flip ndarray horizontally. lr means "Left" and "Right".
   np.fliplr() specialized for horizontal flipping.
   Using flipud function to Reverse a Numpy array 
   The numpy.flipud() function flips the array(entries in each column) in up-down direction, shape preserved.'''

In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("The given array is ", arr,"\n")
rev1=np.fliplr(arr)
print(" Reverse of array using fliplr is",rev1,"\n")
rev3=np.flipud(arr)
print("Reverse of the array using flipud",rev3,"\n")

The given array is  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 Reverse of array using fliplr is [[ 5  4  3  2  1]
 [10  9  8  7  6]] 

Reverse of the array using flipud [[ 6  7  8  9 10]
 [ 1  2  3  4  5]] 



In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''NumPy arrays are an essential tool for scientific computing.
   However, at times, it becomes necessary to manipulate and analyze specific parts of the data.
   This is where array splitting comes into play, allowing you to break down an array into smaller sub-arrays, making the data more manageable. 
   It is similar to slicing but on a larger scale.
   The split(), hsplit(), vsplit(), and dsplit() functions are important tools for dividing arrays along various axes and dimensions.
   These functions are particularly useful when working with one-dimensional arrays, matrices, or high-dimensional datasets.'''

In [18]:
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(Arr, 3)
print(array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
'''Broadcasting 
   The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operations.
    This process involves certain rules that allow the smaller array to be ‘broadcast’ across the larger one, ensuring that they have compatible shapes for these operations.
    Broadcasting is not limited to two arrays; it can be applied over multiple arrays as well.
    Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops.
    This is because NumPy is implemented in C Programming, which is a very efficient language.
    Vectorization 
 The NumPy vectorize function (np.vectorize) is provided by the Python library. 
 It accepts a nested sequence of objects or a NumPy array as input and returns a single NumPy array or a tuple of NumPy arrays as output. 
 With the addition of the NumPy broadcasting rules, the np vectorize function evaluates pyfunc(user-defined function parameter) over successive tuples of the input arrays, similar to the map function in Python.'''

In [20]:
a = np.array([17, 11, 19]) # 1x3 Dimension array 
print(a) 
b = 3  
print(b)  # Broadcasting happened because of 
# miss match in array Dimension. 
c = a + b  
print(c)

[17 11 19]
3
[20 14 22]


In [ ]:
# Practical Questions 


In [13]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np 
import random 
array=np.random.randint(1,101,size=(3,3))
print("Original array is",array,"\n")
transpose_array= array.T
print("Transpose array is",transpose_array,"\n")

Original array is [[33 72 76]
 [31 18 65]
 [94 10 88]] 

Transpose array is [[33 31 94]
 [72 18 10]
 [76 65 88]] 



In [24]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print("Dimension of array is",arr.ndim,"\n")
arr1=arr.reshape(2,5)
print("array of 2*5 array",arr1,"\n")
arr2=arr.reshape(5,2)
print("array of 5*2",arr2,"\n")

[ 1  2  3  4  5  6  7  8  9 10]
Dimension of array is 1 

array of 2*5 array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

array of 5*2 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 



In [38]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
arr=np.random.rand(4,4)
print("Original array is",arr,"\n")
bordered_array = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Bordered aray is",bordered_array,"\n")
print("shape of bordered array is ",bordered_array.shape)

Original array is [[0.86391358 0.57690476 0.71947608 0.97867866]
 [0.25785046 0.04167665 0.00566321 0.69218367]
 [0.63127995 0.12747364 0.70592396 0.04224447]
 [0.85000827 0.19768386 0.50154195 0.84031567]] 

Bordered aray is [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.86391358 0.57690476 0.71947608 0.97867866 0.        ]
 [0.         0.25785046 0.04167665 0.00566321 0.69218367 0.        ]
 [0.         0.63127995 0.12747364 0.70592396 0.04224447 0.        ]
 [0.         0.85000827 0.19768386 0.50154195 0.84031567 0.        ]
 [0.         0.         0.         0.         0.         0.        ]] 

shape of bordered array is  (6, 6)


In [40]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5
arr=np.arange(10,60,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [55]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element
arr=np.array(['python', 'numpy', 'pandas'])
print(arr,"\n")
print("uppercase transformation is",np.char.upper(arr),"\n")
print("lowercase transformation is",np.char.lower(arr),"\n")
print("Capitalizescase is",np.char.capitalize(arr),"\n")
print("titlecase is",np.char.title(arr))

['python' 'numpy' 'pandas'] 

uppercase transformation is ['PYTHON' 'NUMPY' 'PANDAS'] 

lowercase transformation is ['python' 'numpy' 'pandas'] 

Capitalizescase is ['Python' 'Numpy' 'Pandas'] 

titlecase is ['Python' 'Numpy' 'Pandas']


In [59]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
l=["Sachin","Kumar","Giri","Bihar"]
arr=np.array(l)
print(arr,"\n")
new_arr=np.char.join(" ",arr)
print("New array is",new_arr)

['Sachin' 'Kumar' 'Giri' 'Bihar'] 

New array is ['S a c h i n' 'K u m a r' 'G i r i' 'B i h a r']


In [68]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[11,12,13,14],[15,16,17,18]])
print("1st array is:",arr1,"\n")
print("2nd array is:",arr2,"\n")
arr_add=arr1+arr2    # element wise addition 
arr_mul=arr1*arr2    # element wise multiplication
arr_div=arr1/arr2    # element wise divison 
print("addition is:",arr_add,"\n")
print("Multiplication is:",arr_mul,"\n")
print("divison is:",arr_div,"\n")

1st array is: [[1 2 3 4]
 [5 6 7 8]] 

2nd array is: [[11 12 13 14]
 [15 16 17 18]] 

addition is: [[12 14 16 18]
 [20 22 24 26]] 

Multiplication is: [[ 11  24  39  56]
 [ 75  96 119 144]] 

divison is: [[0.09090909 0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471 0.44444444]] 



In [79]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
identity_matrix=np.eye(5,5,dtype=int)
print("The matrix is",identity_matrix,"\n")
print("the diagonal elements are:",np.diag(identity_matrix))

The matrix is [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] 

the diagonal elements are: [1 1 1 1 1]


In [85]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True
arr = np.random.randint(0, 1001, size=100)
prime_numbers = np.array([num for num in arr if is_prime(num)])     # Find all prime numbers in the array
print("Array is :")
print(arr)
print("Prime Numbers:")
print(prime_numbers)

Array is :
[178 209 561 412 295 153 353 264  44 989 824 793 436 877 854 581 255 850
 237 272 337 670 850 848 198 430 812 916 838 453  76 805 750 411 619 624
 787 949 386 555 303 172 673 379 473 636 331 611 961 196 351 289 682 506
 521 287 687 718 103 808 947 428 142 653 480 882  59 695 572 384  36 156
 659 802 689 124 737 527 224 929 901 800 572  36 189 591 751  46 160 255
 717 833 547 617 489 796 816 272  63 156]
Prime Numbers:
[353 877 337 619 787 673 379 331 521 103 947 653  59 659 929 751 547 617]


In [91]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
daily_temperatures = np.random.uniform(15, 30, size=28)
weekly_temperatures = daily_temperatures.reshape(4, -1)       # Reshape the array to represent 4 weeks (28 days) and 2 extra days
weekly_averages = np.mean(weekly_temperatures, axis=1)       # Calculate weekly averages
print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[20.08650948 21.56097508 20.92029773 22.13904397 24.16777702 18.21841285
 19.75499138 21.29951322 20.40180014 27.81240477 20.41343352 28.42748142
 17.72773507 17.55366448 18.08644353 26.80529306 15.01404466 22.58655625
 19.20313771 24.73473565 18.04675436 18.7491596  15.75281568 28.6134822
 15.4441034  20.51024052 15.15742171 20.67801799]

Weekly Averages:
[20.97828679 21.94800466 20.63956646 19.2721773 ]
